OfferZen-Community/developer-mentoring

docs/essential-mentoring-resources/atomic-habits.md, docs/essential-mentoring-resources/giving-and-receiving-feedback/radical-candor.md, docs/essential-mentoring-resources/thinking-partnerships.md, docs/setting-goals/grow-goal-setting-model.md, docs/setting-goals/why-should-you-set-goals.md, docs/the-mentoring-mindset/mentoring-session-agenda.md
See https://docusaurus.io/docs/next/markdown-features/admonitions
Resolves #8
=> Change hints to use remark-admonitions syntax

.gitignore, docusaurus.config.js, package-lock.json, package.json, src/css/custom.css
This doesn't look fantastic, but it works.
=> Search MVP

docs/getting-started-with-mentoring/mentoring-tips-for-success.md, docs/getting-started-with-mentoring/types-of-mentors.md
This is still a WIP. Thrive team is practising how to use GitHub.
=> Adds section on types of mentors

docs/community-resources/big-O/README.md
Added a brief description and a few resource on Big-O notation.
=> Add big-o resource

docusaurus.config.js
Resolves [issue](https://github.com/OfferZen-Community/developer-mentoring/issues/53)
=> Include last modified date in docs

src/css/custom.css
https://github.com/OfferZen-Community/developer-mentoring/issues/71
=> change hover color when in dark mode

docusaurus.config.js
=> Adding github stars to the footer

docs/essential-mentoring-resources/why-should-you-set-goals.md
Issue 91 https://github.com/OfferZen-Community/developer-mentoring/issues/91
Copied the styling from the commented out portion . Happy to change the colours as needed
=> fix (goals): video URL

docusaurus.config.js, package-lock.json, package.json
1. Updates Docusaurus to release candidate
2. Adds plugin-ideal-update #98
=> Plugin ideal image

docs/community-resources/example-goals.md
=> Adding developer mentoring Goal-29 to docs

docs/essential-mentoring-resources/grow-goal-setting-model.md
I'm totally convinced those mistakes were easter eggs :egg:
=> Fix one punctuation issue and a few spelling mistakes

docs/community-resources/example-goals.md
=> Added goals example #5

package-lock.json, package.json, src/theme/DocItem/Footer/index.js
Approach followed:
- Swizzle the DocItemFooter component by the "Wrap" method.
- Add the Giscus React Component underneath it.
=> Add comments feature on docs. Resolves #134

docs/community-resources/example-goals.md
Included my goals summary in example-goals.md spot number #8
=> Updated example-goals.md with goal summary #8

src/css/custom.css
When adding a new article/page, you need to add an escaped route to the css
.menu__link[href*=introduction\/how-to-use-this-handbook]:after, .menu__link[href*=introduction\/about-offerzen]:after
=> customize sidebar css

docs/essential-mentoring-resources/personal-swot-analysis.md, docs/getting-started-with-mentoring/For Mentors/types-of-mentors.mdx
The Vercel build was failing due to broken links in a couple of markdown files. I've fixed the links, so deploys should pass again 🟢
=> Fix broken links

src/css/custom.css
Add custom css to to highlight active menu item (CSS class: menu__link--active)
=> Add feature to highlight active menu item

README.md
fixes #167 
There was a error in the path of a image in README.md.
=> README.md image path fix #167

docs/essential-mentoring-resources/atomic-habits.md
There was an attribution to James Clear's book in the alt text of one of the images, but it's not something you'd see ordinarily.
In this PR I've added an attribution at the bottom, along with a link to the author's page about the book, and some encouragement to the reader to pick up a copy for themselves.
Closes #175.
=> Add attribution to atomic-habits.md

src/data/mentors.json
I've added my details to the mentor list, thanks for setting that up @BenSchZA 🙏
=> Add details to mentor list
